# -*- coding: utf-8 -*-
"""AMAZON SALES DATA ANALYTICS PROJECT Business Intelligence and Data Analytics Using Microsoft Excel and Google Colab (Python).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yC9crWa7GkjjtaH6HO8u3Ckimk2nP93J
"""

# Commented out IPython magic to ensure Python compatibility.
# ==========================================================
# AMAZON SALES DATA ANALYSIS
# Import Required Libraries
# ==========================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Display plots inside Google Colab
# %matplotlib inline

# ==========================================================
# Load Dataset
# ==========================================================

from google.colab import files

uploaded = files.upload()

# Read Excel file
df = pd.read_excel("Amazon_Sales.xlsx")

# Display first five records
df.head()

# ==========================================================
# Dataset Overview
# ==========================================================

print("Number of Rows and Columns")
print(df.shape)

print("\nColumn Names")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nStatistical Summary")
df.describe()

# ==========================================================
# Data Cleaning
# ==========================================================

# Check missing values
print(df.isnull().sum())

# Remove duplicate rows
df = df.drop_duplicates()

# Convert Order Date into datetime format
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

print("Data cleaned successfully.")

# ==========================================================
# KPI Calculations
# ==========================================================

total_sales = df['TotalAmount'].sum()
total_orders = df['OrderID'].nunique()
average_sales = df['TotalAmount'].mean()
maximum_sales = df['TotalAmount'].max()
minimum_sales = df['TotalAmount'].min()

print("Total Sales:", total_sales)
print("Total Orders:", total_orders)
print("Average Sales:", average_sales)
print("Maximum Sales:", maximum_sales)
print("Minimum Sales:", minimum_sales)

# ==========================================================
# Sales by State
# ==========================================================

sales_state = (
    df.groupby('State')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

sales_state

# ==========================================================
# Sales by Category
# ==========================================================

sales_category = (
    df.groupby('Category')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

sales_category

# ==========================================================
# Sales by Sub-Category
# ==========================================================

# The 'Sub-Category' column is not present in the dataset.
# This analysis has been removed.

# ==========================================================
# Top 5 Customers
# ==========================================================

top_customers = (
    df.groupby('CustomerName')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

top_customers

# ==========================================================
# Quantity Sold by Product
# ==========================================================

quantity_product = (
    df.groupby('ProductName')['Quantity']
      .sum()
      .sort_values(ascending=False)
)

quantity_product

# ==========================================================
# Payment Mode Analysis
# ==========================================================

payment_mode = (
    df['PaymentMethod']
      .value_counts()
)

payment_mode

# ==========================================================
# Monthly Sales Trend
# ==========================================================

df['Month'] = df['OrderDate'].dt.strftime('%B')

monthly_sales = (
    df.groupby('Month')['TotalAmount']
      .sum()
)

monthly_sales

# ==========================================================
# State and Category Analysis
# ==========================================================

state_category = (
    df.groupby(['State','Category'])['TotalAmount']
      .sum()
)

state_category

import matplotlib.pyplot as plt

from google.colab import files
import pandas as pd

# Upload the Excel file
uploaded = files.upload()

# Load the dataset
df = pd.read_excel("Amazon_Sales.xlsx")

# Display first five rows
df.head()

print(df.columns.tolist())

import matplotlib.pyplot as plt

# Sales by Category
sales_category = (
    df.groupby('Category')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

print(sales_category)

# Plot Pie Chart
plt.figure(figsize=(8, 8))

sales_category.plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90
)

plt.ylabel("")
plt.title("Sales by Category")
plt.tight_layout()

plt.show()

sales_state = (
    df.groupby('State')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

plt.figure(figsize=(12,6))
sales_state.plot(kind='bar')

plt.title("Sales by State")
plt.xlabel("State")
plt.ylabel("Total Sales")

plt.xticks(rotation=90)
plt.tight_layout()

plt.show()

top_customers = (
    df.groupby('CustomerName')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

print(top_customers)

payment_method = df['PaymentMethod'].value_counts()

print(payment_method)

plt.figure(figsize=(8,5))
payment_method.plot(kind='bar')

plt.title("Orders by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Number of Orders")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

# ==========================================================
# AMAZON SALES DATA ANALYSIS
# Complete Python Analysis
# ==========================================================

# Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
from google.colab import files

# Upload Dataset
uploaded = files.upload()

# Read Excel File
df = pd.read_excel("Amazon_Sales.xlsx")

# ==========================
# Data Cleaning
# ==========================

# Remove duplicates
df = df.drop_duplicates()

# Convert Order Date
df['OrderDate'] = pd.to_datetime(df['OrderDate'])

# ==========================
# Dataset Overview
# ==========================

print("="*50)
print("DATASET OVERVIEW")
print("="*50)

print("Rows and Columns:", df.shape)

print("\nColumn Names")
print(df.columns)

print("\nData Types")
print(df.dtypes)

print("\nStatistical Summary")
print(df.describe())

# ==========================
# KPI Analysis
# ==========================

total_sales = df['TotalAmount'].sum()
total_orders = df['OrderID'].nunique()
average_sales = df['TotalAmount'].mean()
maximum_sale = df['TotalAmount'].max()
minimum_sale = df['TotalAmount'].min()

print("\n==============================")
print("KEY PERFORMANCE INDICATORS")
print("==============================")

print(f"Total Sales: ${total_sales:,.2f}")
print(f"Total Orders: {total_orders}")
print(f"Average Sales: ${average_sales:,.2f}")
print(f"Maximum Sale: ${maximum_sale:,.2f}")
print(f"Minimum Sale: ${minimum_sale:,.2f}")

# ==========================================================
# SALES BY STATE
# ==========================================================

sales_state = (
    df.groupby('State')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

print("\nSales by State")
print(sales_state)

plt.figure(figsize=(12,6))

sales_state.plot(kind='bar')

plt.title("Sales by State")
plt.xlabel("State")
plt.ylabel("Total Sales")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# ==========================================================
# SALES BY CATEGORY
# ==========================================================

sales_category = (
    df.groupby('Category')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
)

print("\nSales by Category")
print(sales_category)

plt.figure(figsize=(8,8))

sales_category.plot(
    kind='pie',
    autopct='%1.1f%%',
    startangle=90
)

plt.ylabel("")
plt.title("Sales by Category")

plt.tight_layout()
plt.show()

# ==========================================================
# TOP 5 CUSTOMERS
# ==========================================================

top_customers = (
    df.groupby('CustomerName')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
      .head(5)
)

print("\nTop 5 Customers")
print(top_customers)

# ==========================================================
# TOP 10 PRODUCTS
# ==========================================================

top_products = (
    df.groupby('ProductName')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

print("\nTop 10 Products")
print(top_products)

plt.figure(figsize=(12,6))

top_products.sort_values().plot(kind='barh')

plt.title("Top 10 Products by Sales")
plt.xlabel("Sales")

plt.tight_layout()
plt.show()

# ==========================================================
# PAYMENT METHOD ANALYSIS
# ==========================================================

payment = df['PaymentMethod'].value_counts()

print("\nPayment Method Analysis")
print(payment)

plt.figure(figsize=(8,5))

payment.plot(kind='bar')

plt.title("Orders by Payment Method")
plt.xlabel("Payment Method")
plt.ylabel("Number of Orders")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# ==========================================================
# MONTHLY SALES TREND
# ==========================================================

df['Month'] = df['OrderDate'].dt.month_name()

month_order = [
    'January','February','March','April','May','June',
    'July','August','September','October','November','December'
]

df['Month'] = pd.Categorical(
    df['Month'],
    categories=month_order,
    ordered=True
)

monthly_sales = (
    df.groupby('Month', observed=False)['TotalAmount']
      .sum()
)

print("\nMonthly Sales")
print(monthly_sales)

plt.figure(figsize=(12,5))

monthly_sales.plot(
    kind='line',
    marker='o',
    linewidth=2
)

plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Total Sales")

plt.grid(True)

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# ==========================================================
# MULTI-LEVEL ANALYSIS
# ==========================================================

state_category = (
    df.groupby(['State','Category'])['TotalAmount']
      .sum()
)

print("\nSales by State and Category")
print(state_category)

# ==========================================================
# BUSINESS INSIGHTS
# ==========================================================

print("\n" + "="*50)
print("BUSINESS INSIGHTS")
print("="*50)

print("1. Identify the state with the highest sales.")
print("2. Determine the category contributing the most revenue.")
print("3. Identify the top 5 customers.")
print("4. Identify the most preferred payment method.")
print("5. Review the monthly sales trend for seasonal patterns.")
print("6. Focus on low-performing states for future marketing campaigns.")

top_products = (
    df.groupby('ProductName')['TotalAmount']
      .sum()
      .sort_values(ascending=False)
      .head(10)
)

plt.figure(figsize=(12,7))

top_products.sort_values().plot(kind='barh')

plt.title("Top 10 Products by Sales")

plt.xlabel("Sales")

plt.show()

print("BUSINESS INSIGHTS")

print("1. The highest-performing state contributes the largest share of revenue.")
print("2. The top product categories drive most sales.")
print("3. Top customers are important for customer retention strategies.")
print("4. Preferred payment modes should be prioritized.")
print("5. Monthly trends can guide promotional campaigns.")

print("RECOMMENDATIONS")

print("1. Increase inventory for high-performing products.")
print("2. Invest more marketing resources in underperforming states.")
print("3. Reward loyal customers with targeted offers.")
print("4. Schedule major campaigns during peak sales months.")

